org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
gpr.user=fadyZaherEng
gpr.key=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
github.user=fadyZaherEng
github.token=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